apiVersion: v1
kind: ConfigMap
metadata:
  name: {{PROJECT_NAME}}-config
  namespace: {{K8S_NAMESPACE}}
  labels:
    app: {{PROJECT_NAME}}
data:
  api-url: "http://{{PROJECT_NAME}}-server-service:3000"
