apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{PROJECT_NAME}}-postgres-pvc
  namespace: {{K8S_NAMESPACE}}
  labels:
    app: {{PROJECT_NAME}}-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{POSTGRES_STORAGE_SIZE}}
  storageClassName: {{K8S_STORAGE_CLASS}}
