apiVersion: v1
kind: Secret
metadata:
  name: {{PROJECT_NAME}}-secrets
  namespace: {{K8S_NAMESPACE}}
  labels:
    app: {{PROJECT_NAME}}
type: Opaque
stringData:
  database-url: "postgresql://user:password@postgres-service:5432/{{POSTGRES_DB}}"
  jwt-secret: "{{JWT_SECRET}}"
