apiVersion: v1
kind: Service
metadata:
  name: {{PROJECT_NAME}}-server-service
  namespace: {{K8S_NAMESPACE}}
  labels:
    app: {{PROJECT_NAME}}-server
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{PROJECT_NAME}}-server
