apiVersion: v1
kind: Service
metadata:
  name: {{PROJECT_NAME}}-web-service
  namespace: {{K8S_NAMESPACE}}
  labels:
    app: {{PROJECT_NAME}}-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{PROJECT_NAME}}-web
